### ISSUE TITLE
Business Rules : Total Cost : Unable to save values

### ISSUE THREAD

**Issue by srinivasnrao** [SAP-samples/teched2020-DEV163#2]
Hello,

I try putting the comparison operator in the "Total Cost" column and it still does not accept and keeps giving me this error.

![image](https://user-images.githubusercontent.com/70371435/102993370-11e0c280-4543-11eb-8fb1-45d59b81b829.png)

What is the right way to put the values ? I have also tried via IMPORT option, but it still fails.

Thanks & Regards
Srinivas Rao.

**Comment by ArchanaShukla** [comment]
Hello Srinivas, 
can you upload the screenshot of the decision table expression as well, together with the condition header.

**Comment by srinivasnrao** [comment]
Closing the issue - since I had put the data type of "Total Cost" as String instead of Number. After changing it to "Number", it worked fine.
