### ISSUE TITLE
"Rework" decision does not bring task to Inbox

### ISSUE THREAD

**Issue by srinivasnrao** [SAP-samples/teched2020-DEV163#3]
Hello Team,

I was able to successfully generate the workflow instance and on the LM level, I took the decision to "rework". The rework path was chosen correctly, but the task did not go the inbox ( but in the log it shows that the recipient is the same user ). Below are the screenshots.

**Execution Log:** -

![image](https://user-images.githubusercontent.com/70371435/103003550-ff708400-4556-11eb-9d3b-d6b0fe19786e.png)

**Workflow Context: -**

![image](https://user-images.githubusercontent.com/70371435/103003625-1c0cbc00-4557-11eb-8ada-aef02778c242.png)

**On Click of task instance, it is observed that the processor is empty: -**

![image](https://user-images.githubusercontent.com/70371435/103003696-3fd00200-4557-11eb-836c-601ea47eff28.png)

Could you please let me know what could be the issue ?

Thanks & Regards
Srinivas Rao,

**Comment by ArchanaShukla** [comment]
Hello Srinivas, you can see additional quotes in the recipient name. Remove the quotes while entering in User Task properties. You have two options (a) Either click Assign Processor and enter your email (without quotes), or (b) Update the workflow definition, build and deploy again. Then create a new instance.

**Comment by srinivasnrao** [comment]
Hi Archana - Thanks. Indeed that was the case ! :)
