### ISSUE TITLE
Deployment termined by Signal SIGPIPE

### ISSUE THREAD

**Issue by srinivasnrao** [SAP-samples/teched2020-DEV163#4]
Hello @ArchanaShukla  - Why do I keep getting this for every deployment? Is there anything that I am missing from perspective of setting up the BAS or something else ?

![image](https://user-images.githubusercontent.com/70371435/103088152-ec6dba80-460f-11eb-89e3-72e4719bc691.png)

Thanks & Regards
Srinivas Rao.

**Comment by ArchanaShukla** [comment]
Hello @srinivasnrao,
This is an information message informing that MTA deployment has finished. It is nothing related to BAS settings. There have been request raised to BAS to improve the deployment message.

**Comment by ArchanaShukla** [comment]
As I have not received any response, closing this ticket. Please reopen if you have further queries.
