### ISSUE TITLE
Excercise1 / not able to get result form 'Retrieve Approval Steps'

### ISSUE THREAD

**Issue by JBRT01** [SAP-samples/teched2020-DEV163#5]
Dear @ArchanaShukla,

Thank you for this exhaustive test script.
Yet I'm unable to get past the 'Retrieve Approval Steps' service task.

I don't have the option to select the 'DetermineLocalApprovers' from the 'Decisions' tab in the 'Capital Expenditure Approval Process'.
![image](https://user-images.githubusercontent.com/82172296/114067668-5f3c3200-989d-11eb-8e7a-57f3b183ceff.png)

I'm also not sure 
- which key I should use for the ruleServiceId variable and where to find it
- which data to fill in for RuleServiceRevision

Can you please advice :)

Gr,
Jonas

**Comment by ArchanaShukla** [comment]
Hello Jonas, 
you seem to have imported Capital Expenditure package, instead you have to import **Sample Capital Expenditure** package.

**Comment by JBRT01** [comment]
Dear @ArchanaShukla,
Oh wow, an essential mistake in the beginning.
Thank you for this sharp eyed clarification.
